# Figure captions

Figure\ 1. The three phases of a hips-eyes lifting movement: the pulling (1-20% of the trial duration), lifting (21-60%) and dropping phases (61-100%).

Figure\ 2. Positions of the reflective markers according to @jackson_improvements_2012. Note: the electromyography sensors visible on the figure were not used in the present study.

Figure\ 3. Mean (plain lines) and standard deviation (shaded areas) joint contributions over the time of the trunk and pelvis (TR/PE), sternoclavicular and acromioclavicular joints (SC/AC), glenohumeral joint (GH), and wrist and elbow joints (WR/EL) to the box height. All variables (sex and mass) are averaged.

Figure\ 4. Significant effects found by the statistical parametric mapping (ANOVA) on the interaction sex-mass, sex main effect and  mass main effect for the trunk and pelvis (TR/PE), glenohumeral joint (GH), and wrist and elbow joints (WR/EL). No significant effects were observed for the sternoclavicular and acromioclavicular joints. Each segment represents a supra-threshold clusters over the normalized time. On the mass main effect panel, a color gradient is associated with the amplitude of the mass-related difference (blue when the contribution with the 6\ kg box is higher, red when the contribution with the 12\ kg box is higher). The hatched lines represent an uninterpretable main effect since an interaction is also present on the same range.

Figure\ 5. Joint contribution and post-hoc analysis for the two mass-related comparisons (left: men at 6\ kg vs. men at 12\ kg, right: women at 6\ kg vs. women at 12\ kg). Each comparison has two panels. The upper panel represents the post-hoc analysis where each segment represents a supra-threshold clusters over the normalized time, with a color gradient associated with the amplitude of the mass-related difference (green when the contribution with the 6\ kg box is higher, orange when the contribution with the 12\ kg box is higher). The lower panel represents the joint contribution of men and women over the time for the trunk and pelvis (TR/PE), sternoclavicular and acromioclavicular joints (SC/AC), glenohumeral joint (GH), and wrist and elbow joints (WR/EL).

Figure\ 6. Joint contribution and post-hoc analysis for the four mass-related comparisons (men at 6\ kg vs. women at 6\ kg on the top left panel, men at 12\ kg vs. women at 6\ kg on the top right panel, men at 6\ kg vs. women at 12\ kg on the bottom left panel, men at 12\ kg vs. women at 12\ kg on the bottom right panel). Each comparison has two panels. The upper panel represents the post-hoc analysis where each segment represents a supra-threshold clusters over the normalized time, with a color gradient associated with the amplitude of the sex-related difference (blue when men's contribution is higher, red when women's is higher). The lower panel represents the joint contribution of men and women over the time for the trunk and pelvis (TR/PE), sternoclavicular and acromioclavicular joints (SC/AC), glenohumeral joint (GH), and wrist and elbow joints (WR/EL).

Figure\ 7. Scatter plot of the mean joint contribution during the dropping phase (Y axis) of men and women against the relative mass of the box (X axis) for the wrist and elbow joints (WR/EL) and the glenohumeral joint (GH). A generalized linear regression model was fitted on each grouping variable (plain line) and the corresponding Pearson's linear correlation coefficient is displayed at the top of the figure.

Appendix\ 1. Joint contribution of men (18\ kg) and women (6\ kg) over the time for the trunk and pelvis (TR/PE), sternoclavicular and acromioclavicular joints (SC/AC), glenohumeral joint (GH), and wrist and elbow joints (WR/EL). This sex-related comparison was not included in the statistics to keep a balanced design, as men lifted three masses (6, 12 and 18\ kg) while women lifted two masses (6 and 12\ kg).
